### ISSUE TITLE
lib directory is missing in gitignore

### ISSUE THREAD

**Issue by riemannulus** [reason-seoul/snowpack-rescript-react#2]
It may be confusing because the `lib` directory where the intermediate output is stored is not specified in `.gitignore` when using `create-snowpack-app`. We need to specify the `lib` directory in `.gitignore`. 

Ref. https://github.com/snowpackjs/snowpack/blob/main/create-snowpack-app/cli/createSnowpackApp.js#L115-L118

**Comment by cometkim** [comment]
Fixed at v0.1.0 and create-snowpack-app@latest
